server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

ribbon:                       #ribbon配置（Feign的实现基于Ribbon，因此此配置也适用）
  eager-load:
    enabled: true             #开启饥饿加载模式 让RibbonClient提前加载，而非第一次调用时加载

spring:
  application:
    name: ssaw-user-server
  rabbitmq:
    host: 118.24.38.46
    port: 5672
    username: husen
    password: 521428
    virtual-host: /
  zipkin:
    sender:
      type: rabbit

  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

  datasource:
    url: jdbc:mysql://118.24.38.46:3306/ssaw_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 521428Slyt!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: mergeStat,clientConfigMap,slf4j
      max-active: 10000
      initial-size: 2
      max-wait: 60000
      min-idle: 3
      time-between-eviction-runs-millis: 18000000
      min-evictable-idle-time-millis: 1000000
      validation-query: SELECT1FROMDUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 100
      max-pool-prepared-statement-per-connection-size: 50
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  redis:
    host: 118.24.38.46
    port: 6379
    password: 521428Slyt
    database: 15

feign:
  hystrix:
    enable: true
  httpclient:
    connection-timeout: 20000

inner:                                                                 #内部系统认证配置
  security:
    username: husen
    password: husen
    client-config:
      authenticate-center:
        client-id: StatisticalCertificationCenter
        secret: 521428Slyp!
        redirect-uris: http://baidu.com
        resource-ids: SSAW-USER-RESOURCE
        authorized-grant-types: authorization_code,refresh_token
        scopes: USER_READ,ROLE_READ,USER_WRITE,ROLE_WRITE,USER_ROLE_WRITE
    resource-ant-matchers: /api/**
    resource-id: SSAW-USER-RESOURCE
    resource-config:
      user-query:
        ant-matchers: /api/user/get/*,/api/user/page,/api/user/findById/*
        scope: USER_READ
      user-save:
        ant-matchers: /api/user/save,/api/user/delete/*
        scope: USER_WRITE
